/**
 * One-time setup script.
 * Run: node server/scripts/setup.js
 *
 * Prompts for an admin password, hashes it with bcrypt (cost 12),
 * generates a random JWT_SECRET, then writes server/.env.
 *
 * Safe to re-run — will overwrite the existing .env.
 */

import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ENV_PATH = path.join(__dirname, '..', '.env');

function ask(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => rl.question(question, (ans) => { rl.close(); resolve(ans.trim()); }));
}

async function main() {
  console.log('\n=== Portfolio Admin Setup ===\n');

  // Check if .env already exists
  if (fs.existsSync(ENV_PATH)) {
    const overwrite = await ask('.env already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Cancelled.');
      process.exit(0);
    }
  }

  const password = await ask('Enter admin password: ');
  if (password.length < 8) {
    console.error('Password must be at least 8 characters.');
    process.exit(1);
  }

  const confirm = await ask('Confirm password: ');
  if (password !== confirm) {
    console.error('Passwords do not match.');
    process.exit(1);
  }

  console.log('\nHashing password (this may take a moment)...');
  const hash = await bcrypt.hash(password, 12);
  const jwtSecret = crypto.randomBytes(48).toString('hex');

  const cloudinaryNote = '# Fill in your Cloudinary credentials to use cloud image storage\n# Leave blank to use local disk storage instead\n';

  const envContent = [
    '# Portfolio Admin — generated by setup.js',
    `# Created: ${new Date().toISOString()}`,
    '',
    `ADMIN_HASH=${hash}`,
    `JWT_SECRET=${jwtSecret}`,
    '',
    '# Image storage: "local" (default) or "cloudinary"',
    'IMAGE_STORAGE=local',
    '',
    cloudinaryNote,
    'CLOUDINARY_CLOUD_NAME=',
    'CLOUDINARY_API_KEY=',
    'CLOUDINARY_API_SECRET=',
    '',
    '# Server port (default: 3001)',
    '# PORT=3001',
  ].join('\n');

  fs.writeFileSync(ENV_PATH, envContent, 'utf8');

  console.log(`\n✓ server/.env written successfully.`);
  console.log('  → ADMIN_HASH set');
  console.log('  → JWT_SECRET generated (96 hex chars)');
  console.log('\nNext steps:');
  console.log('  npm run dev:full');
  console.log('  Visit http://localhost:5174/admin\n');
}

main().catch((err) => { console.error(err); process.exit(1); });
